apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7233
              name: frontend
          env:
            - name: DB
              value: "postgres12"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-user
            - name: POSTGRES_PWD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: postgresql-password
            - name: POSTGRES_SEEDS
              value: "postgresql"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: NAMESPACE_PLACEHOLDER
  labels:
    app: temporal
spec:
  type: ClusterIP
  ports:
    - port: 7233
      targetPort: 7233
      protocol: TCP
      name: frontend
  selector:
    app: temporal
