#!/bin/bash

# Interactive configuration script for local development
# This script helps you set up your local environment without hardcoding values in the repo

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$PROJECT_ROOT/.env.local"

echo "========================================"
echo "Local Configuration Setup"
echo "========================================"
echo ""
echo "This script will help you configure your local environment."
echo "Your selections will be saved to .env.local (not committed to git)"
echo ""

# Function to select from a list
select_option() {
    local prompt="$1"
    shift
    local options=("$@")

    echo "$prompt" >&2
    PS3="Enter number: "
    select opt in "${options[@]}" "Skip" "Enter manually"; do
        case "$REPLY" in
            $(( ${#options[@]} + 1 )))
                echo "SKIP"
                return
                ;;
            $(( ${#options[@]} + 2 )))
                read -p "Enter value: " manual_input >&2
                echo "$manual_input"
                return
                ;;
            *)
                if [ -n "$opt" ]; then
                    echo "$opt"
                    return
                else
                    echo "Invalid selection. Try again." >&2
                fi
                ;;
        esac
    done
}

# Check if .env.local exists
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  .env.local already exists."
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [ "$overwrite" != "y" ] && [ "$overwrite" != "Y" ]; then
        echo "Cancelled. Your existing configuration was not changed."
        exit 0
    fi
    echo ""
fi

# Initialize configuration
echo "# Local Configuration (DO NOT COMMIT)" > "$ENV_FILE"
echo "# Generated by setup-local-config.sh on $(date)" >> "$ENV_FILE"
echo "" >> "$ENV_FILE"

# 1. GCP Project ID
echo "========================================  "
echo "Step 1: GCP Project ID"
echo "========================================"
echo ""

if command -v gcloud &> /dev/null; then
    echo "Detecting GCP projects..."
    projects=$(gcloud projects list --format="value(projectId)" 2>/dev/null || echo "")

    if [ -n "$projects" ]; then
        # Convert to array (compatible with both bash and zsh)
        IFS=$'\n' read -d '' -r -a project_array <<< "$projects" || true
        current_project=$(gcloud config get-value project 2>/dev/null || echo "")

        if [ -n "$current_project" ]; then
            echo "Current gcloud project: $current_project"
            echo ""
        fi

        selected_project=$(select_option "Select GCP Project:" "${project_array[@]}")

        echo "" >&2  # Add newline for clarity

        if [ "$selected_project" = "SKIP" ]; then
            echo "GCP_PROJECT_ID=" >> "$ENV_FILE"
        else
            echo "GCP_PROJECT_ID=$selected_project" >> "$ENV_FILE"
            echo "✓ Selected project: $selected_project" >&2
        fi
    else
        read -p "Enter GCP Project ID (or press Enter to skip): " project_id
        echo "GCP_PROJECT_ID=$project_id" >> "$ENV_FILE"
    fi
else
    echo "gcloud CLI not found. Skipping automatic project detection."
    read -p "Enter GCP Project ID (or press Enter to skip): " project_id
    echo "GCP_PROJECT_ID=$project_id" >> "$ENV_FILE"
fi
echo ""

# 2. Kubernetes Context
echo "========================================"
echo "Step 2: Kubernetes Context"
echo "========================================"
echo ""

if command -v kubectl &> /dev/null; then
    echo "Detecting Kubernetes contexts..."
    contexts=$(kubectl config get-contexts -o name 2>/dev/null || echo "")

    if [ -n "$contexts" ]; then
        # Convert to array (compatible with both bash and zsh)
        IFS=$'\n' read -d '' -r -a context_array <<< "$contexts" || true
        current_context=$(kubectl config current-context 2>/dev/null || echo "")

        if [ -n "$current_context" ]; then
            echo "Current context: $current_context"
            echo ""
        fi

        selected_context=$(select_option "Select Kubernetes context:" "${context_array[@]}")

        echo "" >&2  # Add newline for clarity

        if [ "$selected_context" = "SKIP" ]; then
            echo "K8S_CONTEXT=" >> "$ENV_FILE"
        else
            echo "K8S_CONTEXT=$selected_context" >> "$ENV_FILE"
            echo "✓ Selected context: $selected_context" >&2
        fi
    else
        read -p "Enter Kubernetes context (or press Enter to skip): " context
        echo "K8S_CONTEXT=$context" >> "$ENV_FILE"
    fi
else
    echo "kubectl not found. Skipping automatic context detection."
    read -p "Enter Kubernetes context (or press Enter to skip): " context
    echo "K8S_CONTEXT=$context" >> "$ENV_FILE"
fi
echo ""

# 3. Kubernetes Namespace
echo "========================================"
echo "Step 3: Kubernetes Namespace"
echo "========================================"
echo ""

if command -v kubectl &> /dev/null && [ -n "$selected_context" ] && [ "$selected_context" != "SKIP" ]; then
    echo "Detecting namespaces in context '$selected_context'..."

    # Try to switch context first
    if kubectl config use-context "$selected_context" &>/dev/null; then
        # Add timeout to prevent hanging
        namespaces=$(timeout 5s kubectl get namespaces -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "")
    else
        echo "Warning: Could not switch to context '$selected_context'"
        namespaces=""
    fi

    if [ -n "$namespaces" ]; then
        # Convert to array (compatible with both bash and zsh)
        IFS=$'\n' read -d '' -r -a namespace_array <<< "$(echo $namespaces | tr ' ' '\n')" || true

        selected_namespace=$(select_option "Select Kubernetes namespace:" "${namespace_array[@]}")

        echo "" >&2  # Add newline for clarity

        if [ "$selected_namespace" = "SKIP" ]; then
            echo "K8S_NAMESPACE=default" >> "$ENV_FILE"
        else
            echo "K8S_NAMESPACE=$selected_namespace" >> "$ENV_FILE"
            echo "✓ Selected namespace: $selected_namespace" >&2
        fi
    else
        read -p "Enter Kubernetes namespace (default): " namespace
        namespace="${namespace:-default}"
        echo "K8S_NAMESPACE=$namespace" >> "$ENV_FILE"
    fi
else
    read -p "Enter Kubernetes namespace (default): " namespace
    namespace="${namespace:-default}"
    echo "K8S_NAMESPACE=$namespace" >> "$ENV_FILE"
fi
echo ""

# 4. MongoDB Configuration
echo "========================================"
echo "Step 4: MongoDB Credentials"
echo "========================================"
echo ""

echo "Generate MongoDB password options:"
echo "  1) Auto-generate strong password (recommended)"
echo "  2) Enter your own password"
echo ""
read -p "Choose option (1 or 2): " mongo_option

if [ "$mongo_option" = "2" ]; then
    read -s -p "Enter MongoDB password: " mongo_password
    echo ""
    read -s -p "Confirm password: " mongo_password_confirm
    echo ""

    if [ "$mongo_password" != "$mongo_password_confirm" ]; then
        echo "❌ Passwords don't match!"
        exit 1
    fi
else
    # Auto-generate strong password
    mongo_password=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
    echo "✓ Generated strong password (32 characters)" >&2
fi

# MongoDB username
read -p "MongoDB username (admin): " mongo_username
mongo_username="${mongo_username:-admin}"

echo "MONGODB_USERNAME=$mongo_username" >> "$ENV_FILE"
echo "MONGODB_PASSWORD=$mongo_password" >> "$ENV_FILE"
echo "MONGODB_DATABASE=honey-store" >> "$ENV_FILE"
echo "✓ MongoDB credentials saved to .env.local" >&2

echo ""

# 5. Artifact Registry Configuration
echo "========================================"
echo "Step 5: Artifact Registry Configuration"
echo "========================================"
echo ""

read -p "Artifact Registry location (us-east1): " ar_location
ar_location="${ar_location:-us-east1}"

read -p "Artifact Registry repo name (docker-repo): " ar_repo
ar_repo="${ar_repo:-docker-repo}"

echo "ARTIFACT_REGISTRY_LOCATION=$ar_location" >> "$ENV_FILE"
echo "ARTIFACT_REGISTRY_REPO=$ar_repo" >> "$ENV_FILE"
echo "USE_GCR=true" >> "$ENV_FILE"
echo "✓ Artifact Registry: $ar_location / $ar_repo" >&2

echo ""

# 6. Ingress Configuration
echo "========================================"
echo "Step 6: Ingress with TLS (optional)"
echo "========================================"
echo ""

read -p "Do you want to set up Ingress with TLS? (y/N): " enable_ingress

if [ "$enable_ingress" = "y" ] || [ "$enable_ingress" = "Y" ]; then
    echo "ENABLE_INGRESS=true" >> "$ENV_FILE"

    # Base domain
    read -p "Enter your base domain (e.g., example.com): " base_domain
    if [ -z "$base_domain" ]; then
        echo "❌ Base domain is required for Ingress setup."
        exit 1
    fi
    echo "BASE_DOMAIN=$base_domain" >> "$ENV_FILE"

    # Detect IngressClasses
    echo ""
    echo "Detecting available IngressClasses..."
    ingress_classes=$(kubectl get ingressclass -o jsonpath='{.items[*].metadata.name}' 2>/dev/null || echo "")
    if [ -n "$ingress_classes" ]; then
        echo "Available IngressClasses: $ingress_classes"
    fi
    read -p "Ingress class (nginx): " ingress_class
    ingress_class="${ingress_class:-nginx}"
    echo "INGRESS_CLASS=$ingress_class" >> "$ENV_FILE"

    # TLS secret
    echo ""
    read -p "TLS secret name (e.g., cf-star-tls-cert): " tls_secret
    if [ -n "$tls_secret" ]; then
        echo "TLS_SECRET_NAME=$tls_secret" >> "$ENV_FILE"
        read -p "Namespace to copy TLS secret from (e.g., default): " tls_ns
        if [ -n "$tls_ns" ]; then
            echo "TLS_SECRET_SOURCE_NAMESPACE=$tls_ns" >> "$ENV_FILE"
        fi
    fi

    # Get namespace for host construction
    ns=$(grep "^K8S_NAMESPACE=" "$ENV_FILE" | cut -d= -f2)
    ns="${ns:-default}"

    # Construct hostnames
    FRONTEND_HOST="${ns}-sandbox.${base_domain}"
    DASHBOARD_HOST="${ns}-dashboard-sandbox.${base_domain}"
    API_HOST="${ns}-api-sandbox.${base_domain}"

    echo "FRONTEND_HOST=$FRONTEND_HOST" >> "$ENV_FILE"
    echo "DASHBOARD_HOST=$DASHBOARD_HOST" >> "$ENV_FILE"
    echo "API_HOST=$API_HOST" >> "$ENV_FILE"

    echo ""
    echo "✓ Ingress hosts configured:" >&2
    echo "  Frontend:  $FRONTEND_HOST" >&2
    echo "  Dashboard: $DASHBOARD_HOST" >&2
    echo "  API:       $API_HOST" >&2
else
    echo "ENABLE_INGRESS=false" >> "$ENV_FILE"
    echo "ℹ️  Ingress disabled. Services will use ClusterIP (port-forward or LoadBalancer)."
fi

# 7. PostgreSQL Configuration (for Temporal)
echo ""
echo "========================================"
echo "Step 7: PostgreSQL Credentials (for Temporal)"
echo "========================================"
echo ""

echo "Generate PostgreSQL password options:"
echo "  1) Auto-generate strong password (recommended)"
echo "  2) Enter your own password"
echo ""
read -p "Choose option (1 or 2): " pg_option

if [ "$pg_option" = "2" ]; then
    read -s -p "Enter PostgreSQL password: " pg_password
    echo ""
else
    pg_password=$(openssl rand -base64 32 | tr -d "=+/" | cut -c1-32)
    echo "✓ Generated strong password (32 characters)" >&2
fi

read -p "PostgreSQL username (temporal): " pg_username
pg_username="${pg_username:-temporal}"

echo "POSTGRESQL_USERNAME=$pg_username" >> "$ENV_FILE"
echo "POSTGRESQL_PASSWORD=$pg_password" >> "$ENV_FILE"
echo "✓ PostgreSQL credentials saved to .env.local" >&2

echo ""
echo "========================================"
echo "Configuration Complete!"
echo "========================================"
echo ""
echo "Configuration saved to: $ENV_FILE"
echo ""
echo "Summary:"
echo "--------"
cat "$ENV_FILE" | grep -v "^#" | grep -v "^$" | sed 's/\(PASSWORD=\).*/\1********/'
echo ""
echo "Your deployment scripts will now automatically use these values."
echo ""
echo "To reconfigure, run: ./scripts/setup-local-config.sh"
echo "To view config: cat .env.local"
echo ""
